from django.contrib import admin
from django.urls import path
from myApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('api/chat/', views.chat_api, name='chat_api'),
    path('demo/sop-bot/', views.sop_bot_demo, name='sop_bot_demo'),
    path('demo/booking-bot/', views.booking_bot_demo, name='booking_bot_demo'),
    path('demo/voice-agent/', views.voice_agent_demo, name='voice_agent_demo'),
    path('demo/custom-ai-systems/', views.custom_ai_systems, name='custom_ai_systems'),
    path('demo/geo/', views.geo_demo, name='geo_demo'),
    path('demo/email-automation/', views.email_automation_demo, name='email_automation_demo'),
    path('demo/email-crm/', views.email_crm_demo, name='email_crm_demo'),
    path('api/email/process/', views.process_email_api, name='process_email_api'),
    path('demo/omnichannel-support/', views.omnichannel_support_demo, name='omnichannel_support_demo'),
    path('demo/support-crm/', views.support_crm_demo, name='support_crm_demo'),
    path('api/support/process/', views.process_support_conversation_api, name='process_support_conversation_api'),
    path('demo/qualification/', views.qualification_demo, name='qualification_demo'),
    path('demo/qualification-leads/', views.qualification_leads_demo, name='qualification_leads_demo'),
    path('api/qualification/process/', views.process_qualification_api, name='process_qualification_api'),
    path('demo/automation-engine/', views.automation_engine_demo, name='automation_engine_demo'),
    path('api/automation/run/', views.run_automation_api, name='run_automation_api'),
    path('demo/quality-control/', views.quality_control_demo, name='quality_control_demo'),
    path('api/quality/analyze/', views.analyze_quality_api, name='analyze_quality_api'),
    path('demo/analytics/', views.analytics_demo, name='analytics_demo'),
    path('api/analytics/generate-insights/', views.generate_insights_api, name='generate_insights_api'),
    path('api/analytics/insights/<uuid:insight_id>/create-task/', views.create_insight_task_api, name='create_insight_task_api'),
    path('api/analytics/insights/<uuid:insight_id>/draft-automation/', views.draft_insight_automation_api, name='draft_insight_automation_api'),
    path('api/analytics/insights/<uuid:insight_id>/notify/', views.notify_insight_api, name='notify_insight_api'),
    path('demo/crm-workflow/', views.crm_workflow_demo, name='crm_workflow_demo'),
    path('api/crm/simulate-lead/', views.simulate_crm_lead_api, name='simulate_crm_lead_api'),
    path('api/crm/contacts/<uuid:contact_id>/', views.get_crm_contact_api, name='get_crm_contact_api'),
    path('api/crm/contacts/<uuid:contact_id>/run-automation/', views.run_crm_automation_api, name='run_crm_automation_api'),
    path('demo/extraction/', views.extraction_demo, name='extraction_demo'),
    path('demo/crm/', views.crm_demo, name='crm_demo'),
    path('api/documents/upload/', views.document_upload_api, name='document_upload_api'),
    path('api/extract/', views.extract_api, name='extract_api'),
    path('api/extract/<uuid:run_id>/push/', views.push_to_crm_api, name='push_to_crm_api'),
    path('api/extract/<uuid:run_id>/export.xlsx', views.export_to_spreadsheet, name='export_to_spreadsheet'),
    path('api/crm/webhook/', views.crm_webhook_api, name='crm_webhook_api'),
]