# Generated by Django 5.1.2 on 2026-02-18 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.CharField(max_length=255)),
                ('document_title', models.CharField(max_length=255)),
                ('template_id', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=255)),
                ('extracted_data', models.JSONField()),
                ('validation_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
