# Generated by Django 5.1.2 on 2026-02-18 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_crmrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoEmailResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent', models.CharField(max_length=100)),
                ('urgency', models.CharField(max_length=20)),
                ('sentiment', models.CharField(max_length=20)),
                ('suggested_owner', models.CharField(max_length=255)),
                ('crm_action', models.CharField(max_length=255)),
                ('draft_reply', models.TextField()),
                ('follow_up_hours', models.IntegerField(default=48)),
                ('confidence_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='myApp.demoemail')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
