# Generated by Django 5.1.2 on 2026-02-18 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_demoemail_demoemailresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCRMRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=255)),
                ('email_subject', models.CharField(max_length=500)),
                ('email_from', models.CharField(max_length=255)),
                ('email_from_name', models.CharField(max_length=255)),
                ('intent', models.CharField(max_length=100)),
                ('urgency', models.CharField(max_length=20)),
                ('sentiment', models.CharField(max_length=20)),
                ('assigned_team', models.CharField(max_length=255)),
                ('crm_action', models.CharField(max_length=255)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('crm_record_id', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_up_hours', models.IntegerField(default=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
