# Generated by Django 5.1.2 on 2026-02-18 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_emailcrmrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('web', 'Web Chat'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_message', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myApp.democonversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('assigned_team', models.CharField(max_length=255)),
                ('intent', models.CharField(max_length=100)),
                ('urgency', models.CharField(max_length=20)),
                ('sentiment', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('ai_confidence', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='myApp.democonversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
