# Generated by Django 5.1.2 on 2026-02-18 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_democonversation_demomessage_demoticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=255)),
                ('budget_range', models.CharField(max_length=100)),
                ('service_interest', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.IntegerField(default=0)),
                ('intent', models.CharField(choices=[('strong', 'Strong'), ('moderate', 'Moderate'), ('weak', 'Weak')], default='moderate', max_length=20)),
                ('fit_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('budget_match', models.BooleanField(default=False)),
                ('urgency_days', models.IntegerField(blank=True, null=True)),
                ('assigned_team', models.CharField(blank=True, max_length=255)),
                ('recommended_action', models.CharField(blank=True, max_length=255)),
                ('demo_booked', models.BooleanField(default=False)),
                ('demo_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='myApp.demolead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
