# Generated by Django 5.1.2 on 2026-02-18 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_demolead_demoqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('form_submission', 'Form Submission'), ('instagram_dm', 'Instagram DM'), ('payment_failed', 'Payment Failed'), ('high_score_lead', 'High Score Lead'), ('support_escalation', 'Support Escalation'), ('email_received', 'Email Received'), ('chat_message', 'Chat Message')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoWorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_path', models.JSONField(default=list)),
                ('actions', models.JSONField(default=list)),
                ('confidence_score', models.IntegerField(default=0)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_run', to='myApp.demoevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
