# Generated by Django 5.1.2 on 2026-02-18 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_demoevent_demoworkflowrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('chat', 'Chat'), ('support', 'Support Ticket'), ('social', 'Social Media')], max_length=20)),
                ('message', models.TextField()),
                ('sender_type', models.CharField(max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('conversation_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoRiskAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('sentiment_label', models.CharField(default='neutral', max_length=50)),
                ('churn_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('compliance_flag', models.BooleanField(default=False)),
                ('compliance_type', models.CharField(blank=True, max_length=100)),
                ('severity_score', models.FloatField(default=0.0)),
                ('alert_created', models.BooleanField(default=False)),
                ('automation_paused', models.BooleanField(default=False)),
                ('escalation_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analysis', to='myApp.qualityconversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
