# Generated by Django 5.1.2 on 2026-02-18 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_qualityconversation_demoriskanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('leads', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('sales_qualified_leads', models.IntegerField(default=0)),
                ('deals_closed', models.IntegerField(default=0)),
                ('support_tickets', models.IntegerField(default=0)),
                ('churn_signals', models.IntegerField(default=0)),
                ('average_response_time_minutes', models.IntegerField(default=0)),
                ('channel_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('bottleneck', 'Bottleneck Detection'), ('opportunity', 'Revenue Opportunity'), ('risk', 'Risk Alert'), ('optimization', 'Optimization'), ('pattern', 'Pattern Detection')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('what_happened', models.TextField()),
                ('why_it_matters', models.TextField()),
                ('recommended_action', models.TextField()),
                ('estimated_revenue_lift', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('confidence_score', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='myApp.demoanalyticssnapshot')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
