# Generated by Django 5.1.2 on 2026-06-08 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_crmcontact_crmautomationrun_crmactivity_crmtag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('accent', models.CharField(default='#0040FF', max_length=20)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('read_minutes', models.IntegerField(default=5)),
                ('author', models.CharField(default='KATEK AI', max_length=120)),
                ('published_at', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-published_at'],
            },
        ),
    ]
